CREATE TABLE `eshop`.`order` (
  `id` int(11) NOT NULL AUTO_INCREMENT, 
  `order_no` varchar(32) NOT NULL, 
  `guid` char(32) NOT NULL, 
  `order_date` datetime NOT NULL, 
  `order_status` int(11) NOT NULL, 
  `customer_id` int(11), 
  `customer_email` varchar(45) NOT NULL, 
  `customer_name` varchar(80) NOT NULL, 
  `customer_phone` varchar(20), 
  `delivery_address` varchar(100) NOT NULL, 
  `coupon_code` varchar(20), 
  `invoice_required` tinyint(1) NOT NULL, 
  `invoice_type` int(11), 
  `invoice_title` varchar(40), 
  `paid_time` datetime, 
  `confirmed_time` datetime, 
  `deliver_time` datetime, 
  `delivered_time` datetime, 
  `payment_method` varchar(20), 
  `total_amount` decimal(10,3) NOT NULL, 
  `discounted_amount` decimal(10,3) NOT NULL, 
  `discount_type` int(11) NOT NULL, 
  `delivery_fee` decimal(10,3) NOT NULL, 
  `confirm_user` int(11), 
  `deliver_user` int(11), 
  `transaction_no` varchar(80), 
  `tx` varchar(80), 
  `tx_extra` varchar(200), 
  `hash` char(32) NOT NULL, 
  `cancel_time` datetime, 
  `cancel_reason` varchar(20), 
  `item_count` int(11) NOT NULL, 
  `delivery_method` int(11), 
  `delivery_no` varchar(32), 
  `delivery_confirmed_time` datetime, 
  `finish_time` datetime, 
  `deleted` tinyint(1) NOT NULL, 
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci COMMENT 'Represents the orders. ';