CREATE TABLE `eshop`.`product` (
  `id` int(11) NOT NULL AUTO_INCREMENT, 
  `cid` varchar(100) NOT NULL, 
  `name` varchar(200) NOT NULL, 
  `series_name` varchar(200), 
  `description` varchar(500), 
  `category_id` int(11) NOT NULL, 
  `stock` int(11), 
  `price` decimal(10,3) NOT NULL, 
  `discount_price` decimal(10,3), 
  `discount_keyword` varchar(45), 
  `thumbnail` varchar(255), 
  `thumbnail_image_cords` varchar(45), 
  `original_image` varchar(255), 
  `original_image_width` int(11), 
  `original_image_height` int(11), 
  `production_place` int(11), 
  `extra_word` varchar(45), 
  `shelf_life` varchar(40), 
  `on_shelf` tinyint(1) NOT NULL, 
  `on_shelf_time` datetime, 
  `sales_volume` int(11) NOT NULL, 
  `creator` int(11) NOT NULL, 
  `create_time` datetime NOT NULL, 
  `update_time` datetime, 
  `update_user` int(11), 
  `is_recommended` tinyint(1) NOT NULL, 
  `meta_keyword` varchar(200), 
  `meta_description` varchar(500), 
  `rating` double NOT NULL, 
  `promotion_line` varchar(500), 
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;