CREATE TABLE `eshop`.`rendering_media_item` (
  `id` int(11) NOT NULL AUTO_INCREMENT, 
  `block_id` int(11) NOT NULL, 
  `item_type` int(11) NOT NULL, 
  `item_url` varchar(255), 
  `media_item_id` int(11), 
  `title` varchar(200), 
  `description` varchar(500), 
  `size_spec` int(11) NOT NULL, 
  `data` mediumtext, 
  `css` text, 
  `html_overlay` mediumtext, 
  `html_overlay_editor_data` mediumtext, 
  `thumbnail` varchar(255), 
  `thumbnail_options` varchar(512), 
  `create_time` datetime NOT NULL, 
  `creator` int(11) NOT NULL, 
  `update_time` datetime, 
  `update_user` int(11), 
  `sort_order` int(11) NOT NULL, 
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;